[build]
builder = "NIXPACKS"
buildCommand = "npm install --no-audit --no-fund"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[nixpacks]
rootDirectory = "backend"
